version: '3.1'

services:
  db:
    image: mysql:lts
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/import:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: qwerty